R3Conclave/conclave-core-sdk

- .github/workflows/automerge.yml
- CONTRIBUTING.md
- README.md
- build.gradle
- conclave-client/src/main/kotlin/com/r3/conclave/client/EnclaveTransport.kt
- conclave-web-host/README.md
- containers/README.md
- containers/sdk-build/src/docker/Dockerfile
- cpp/CMakeLists.txt
- cpp/linux-sgx/README.md
- docs/docs/api-changes.md
- docs/docs/conclave-web-host.md
- docs/docs/faq.md
- docs/docs/ide-configuration.md
- docs/docs/index.md
- docs/docs/kds-detail.md
- docs/docs/release-notes.md
- docs/docs/running-hello-world.md
- dokka/README.md
- integration-tests/README.md
- integration-tests/kotlin-enclave/host/src/test/kotlin/com/r3/conclave/integrationtests/kotlin/enclave/ApiKotlinConsumerTest.kt
- settings.gradle
Also changed "Conclave SDK" references to either be more specific by adding "Core" or modified in other ways.
The root README has also been cleaned up.
> CON-1062: Update references to the new conclave-core-sdk repo

- build.gradle
- scripts/ci_publish.sh
This is an add-on to the previous PR https://github.com/R3Conclave/conclave-core-sdk/pull/9, as we missed to specify in the script that we want to publish to Maven Central repo.
We are now publishing to all repositories, including Maven Central
> CON-1020: Publish Conclave SDK to Maven Central (fix publication to all repositories)

- conclave-init/src/test/kotlin/com/r3/conclave/init/CreateProjectTest.kt
- conclave-init/template/client/build.gradle
- conclave-init/template/host/build.gradle
- docs/docs/writing-your-own-enclave-host.md
This stops ugly deprecation warning from being displayed when the project is built.
> Updated conclave-init generated project to not use deprecated Gradle API

- build.gradle
- scripts/ci_publish.sh
After the fixes in the PR here https://github.com/R3Conclave/conclave-core-sdk/pull/13 we have got back a 403 error during publication, due to a wrong legacy Sonatype repository address, while we were given access to the newest Sonatype repository.
This patch fixes this.
> CON-1020: Publish Conclave SDK to Maven Central (fix Sonatype repo address)

- docs/docs/css/r3-branding.css
Currently, links are not distinguishable from standard text on the docs site. Only when a user hovers over the link text the user knows it's a link.
I have changed the color of links by adding a CSS variable '--md-typeset-a-color' in the r3-branding.css file.  I have used a lighter version of teal, which wouldn't stand out too much while being readable. The hex color code is #006c94. Needs to test how it looks when published.
> CON-1138: Make links readable on the docs site

- docs/docs/api-changes.md
- docs/docs/conclave-init.md
- docs/docs/conclave-web-host.md
- docs/docs/ide-configuration.md
- docs/docs/index.md
- docs/docs/known-issues.md
- Scanned the docs site for opportunities to mention open-sourcing and link the GitHub repository.
- Mentioned open source and linked to the GitHub repository on a couple of pages, including the homepage.
- Fixed some typos that I noticed while scanning through all the docs.
> Mention open source and GitHub repository. Fix a few minor typos.

- conclave-host/src/main/kotlin/com/r3/conclave/host/EnclaveHost.kt
- conclave-host/src/main/kotlin/com/r3/conclave/host/Gramine.kt
It is now possible to run Conclave using Gramine but without sgx. This is only experimental and more changes will be added in future commits. To use gramine, Conclave must be built in mock mode and the environment variable CONCLAVE_GRAMINE_ENABLE must be set.
The class EnclaveScanner was created to group together all the functions responsible for searching for enclaves.
> CON-1161 - Integrated gramine Conclave and refactored the code

- docs/docs/api-changes.md
- docs/docs/architecture.md
- docs/docs/renewability.md
When a user clicks on some API links on the docs site, the pages don't render correctly. I investigated all the API links on our docs site and fixed the ones which were not displaying correctly—also fixed a few typos that caught my eye. Note that this is not a thorough rewrite of the docs that are changed by this PR.
> CON-1170: Review API links

- docs/docs/enclave-configuration.md
This is a minor change to correct an outdated link to the GraalVM manual.
> Update reflection configuration files link

- conclave-common/src/main/kotlin/com/r3/conclave/common/EnclaveConstraint.kt
- conclave-common/src/test/kotlin/com/r3/conclave/common/EnclaveConstraintTest.kt
Updated how the security level is assess. If the security level is set to INSECURE then a client can only communicate with an enclave that is running as INSECURE. If the security level is set to STALE then the client can communicate with a STALE or SECURE enclave. If the security level is set to SECURE then the client can only communicate with a SECURE enclave. This prevents clients from connecting to enclaves running in production by mistake or by a malicious host. Check CON-806 for more details.
Updated the unit-tests file.
> CON-806 - Review INSECURE, STALE, and SECURE enclave constraint options

- cpp/jvm-enclave-common/stubs/unistd.cpp
- Attempts to create symlinks or hardlinks inside the enclave will no longer cause the enclave to crash. An exception is thrown to the user instead.
```
java.nio.file.FileSystemException: (symlink|link) -> <link-directory>: 
at sun.nio.fs.UnixFileSystemProvider.createLink(UnixFileSystemProvider.java:491)
at java.nio.file.Files.createLink(Files.java:1112)
at com.r3.conclave.sample.enclave.ReverseEnclave.onStartup(ReverseEnclave.java:23)
at com.r3.conclave.enclave.Enclave$StartCallHandler.handleCall(Enclave.kt:580)
at com.r3.conclave.common.internal.CallInterface.handleIncomingCall(CallInterface.kt:48)
at com.r3.conclave.enclave.internal.NativeEnclaveHostInterface.handleCallECall(NativeEnclaveHostInterface.kt:93)
at com.r3.conclave.enclave.internal.NativeEnclaveHostInterface.handleECall(Nati …
```
> [CON-861] [CON-862] Stop symlinks/hardlinks from causing enclave crash

- cpp/jvm-enclave-common/stubs/dlfcn.cpp
- cpp/jvm-enclave-common/stubs/ioctl.cpp
- cpp/jvm-enclave-common/stubs/stdio.cpp
- cpp/jvm-enclave-common/stubs/sys_poll.cpp
- cpp/jvm-enclave-common/stubs/sys_socket.cpp
- cpp/jvm-enclave-common/stubs/sys_stat.cpp
- cpp/jvm-enclave-common/stubs/unistd.cpp
- integration-tests/general/common/src/main/kotlin/com/r3/conclave/integrationtests/general/common/tasks/CreateSocket.kt
- integration-tests/general/common/src/main/kotlin/com/r3/conclave/integrationtests/general/common/tasks/EnclaveTestAction.kt
- integration-tests/general/common/src/main/kotlin/com/r3/conclave/integrationtests/general/common/tasks/FileSystemActions.kt
- integration-tests/general/tests/build.gradle
- integration-tests/general/tests/src/test/kotlin/com/r3/conclave/integrationtests/general/tests/EnclaveHostNativeTest.kt
- integration-tests/general/tests/src/test/kotlin/com/r3/conclave/integrationtests/general/tests/filesystem/FileSystemEnclaveTest.kt
- integration-tests/general/tests/src/test/kotlin/com/r3/conclave/integrationtests/general/tests/filesystem/PathsTest.kt
Many Linux Posix functions were previously stubbed in such a way that the enclave would abort when these were called.
We now want to return an error instead, so that it is up to the JVM (whose bytecode gets compiled with Native Image) interacting with the Posix calls to handle errors.
This PR also adds tests for the symbolic and hard link (https://r3-cev.atlassian.net/browse/CON-861, https://r3-cev.atlassian.net/browse/CON-862)
> CON-1133, CON-1188: Make stubbed functions to return an error

- conclave-init/template/host/build.gradle
- docs/docs/conclave-web-host.md
- docs/docs/mockmode.md
- docs/docs/writing-your-own-enclave-host.md
- test-conclave-init.sh
- versions.gradle
The projects generated by `conclave-init` will now have a default logging framework. 
Updated io.spring.dependency-management to the latest version (1.1.0).
Added a check to ensure the host generates logs by default.
> CON-1193 - conclave init - Added a logging framework to be used as default by the projects generated using the conclave-init tool

- conclave-client/src/main/kotlin/com/r3/conclave/client/EnclaveClient.kt
- conclave-common/src/main/kotlin/com/r3/conclave/common/EnclaveInstanceInfo.kt
- conclave-enclave/src/main/kotlin/com/r3/conclave/enclave/Enclave.kt
- conclave-mail/src/main/kotlin/com/r3/conclave/mail/PostOffice.kt
- docs/docs/mail.md
This is to update the docs site by matching the changes in the [other PR](https://github.com/R3Conclave/conclave-core-sdk/pull/89). Merging to release/1.3 branch.
> CON-523: Fix Dokka API documentation on docs site

- plugin-enclave-gradle/src/main/kotlin/com/r3/conclave/plugin/enclave/gradle/GradleEnclavePlugin.kt
QA tests are currently failing because this is where we use a different technique to deploy our host applications.
In QA we generate call `distZip`, `distTar` tasks in order to bundle the host, upload it to the CRAFT VMs and unzip it.
We have a bug when the host had multiple enclaves: we use the same name for different "enclave bundle" jars. Even though these jars are actually present in differently named directories, when we call `distZip` we actually take them out of the "directory structure" context and therefore they are conflicting.
This causes issues in QA: Gradle complains about a missing strategy to handle this. 
Changing the name as we do in this PR should solve this problem
> CON-1187: Fix QA tests by changing the name of "enclave-bundle" jars

- docs/docs/api-changes.md
- docs/docs/enclave-configuration.md
- integration-tests/python-enclave/enclave/build.gradle
- plugin-enclave-gradle/src/main/kotlin/com/r3/conclave/plugin/enclave/gradle/ConclaveExtension.kt
- plugin-enclave-gradle/src/main/kotlin/com/r3/conclave/plugin/enclave/gradle/GradleEnclavePlugin.kt
- plugin-enclave-gradle/src/main/kotlin/com/r3/conclave/plugin/enclave/gradle/gramine/GenerateGramineDirectManifest.kt
The default value of `enclave_worker_threads` is set to 10.
Gramine's maximum threads will no longer be twice the value set in the `maxThreads` but instead the exact value provided in the `maxThreads` configuration field.
`maxThreads` default value has been set to 100. This value should cover most of the use-cases and it does not degrade the enclave performance nor does increases the memory usage of an enclave.
Removed the `maxThreads` configuration field from `integration-tests/python-enclave/enclave/build.gradle`
The docs were updated to include the new default value set for the maxThreads.
> CON-1223 - Updated the default values of maxThreads and the enclave_worker_threads.

- integration-tests/general/common-test/src/main/kotlin/com/r3/conclave/integrationtests/general/commontest/TestUtils.kt
- integration-tests/plugin-tests/src/test/kotlin/com/r3/conclave/integrationtests/general/tests/plugin/GraalVMEnclaveBundleJarTest.kt
- plugin-enclave-gradle/src/main/kotlin/com/r3/conclave/plugin/enclave/gradle/ConclaveExtension.kt
- plugin-enclave-gradle/src/main/kotlin/com/r3/conclave/plugin/enclave/gradle/EnclaveExtension.kt
- plugin-enclave-gradle/src/main/kotlin/com/r3/conclave/plugin/enclave/gradle/GradleEnclavePlugin.kt
Certain input file parameters in the enclave's Gradle config may not exist when the build process begins. These include `mrsignerSignature` and `signingMaterial`. These particular files are only created in the first-pass of the `externalKey` signing process (when `generateEnclaveSigningMaterial` is invoked), and their existence is only required in the second-pass.
The previous changes to make sure all the plugin tasks are "incremental" incorrectly marked the `EnclaveExtension` config objects as inputs to the `GenerateEnclaveProperties` task. `GenerateEnclaveProperties` only needs the properties of the parent `ConclaveExtension` object as inputs. To fix this, the `release`, `debug`, and `simulation` properties are now marked as `@Internal` and not `@Nested`.
> CON-1235: Fix issue with Gradle checking for input files are may not exist

- containers/aesmd/Dockerfile
- containers/integration-tests-build/Dockerfile
- integration-tests/general/tests/src/test/kotlin/com/r3/conclave/integrationtests/general/tests/ThreadSafeEnclaveTests.kt
- integration-tests/general/threadsafe-enclave/build.gradle
With the previous changes we have introduced the AESM service. This works but it is currently throwing an exception related to missing certificates. The root cause of the problem is that AESM service needs the Azure DCAP Client in order to retrieve such certificates and therefore we need to add it to the related AESM container.
This PR adds that.
In order to make an integration test pass (`MockEnclaveEnvironmentHardwareCompatibilityTest`), we also have to increase the `maxThread` value of the enclave used in that test
> CON-1178: Fix certificate issues of AESM service

- containers/conclave-build/Dockerfile
- containers/scripts/ci_build_publish_docker_images.sh
- containers/scripts/common.sh
- containers/sdk-build/src/docker/Dockerfile
- plugin-enclave-gradle/build.gradle
- plugin-enclave-gradle/src/main/kotlin/com/r3/conclave/plugin/enclave/gradle/GradleEnclavePlugin.kt
- plugin-enclave-gradle/src/main/kotlin/com/r3/conclave/plugin/enclave/gradle/LinuxExec.kt
- versions.gradle
In this patch we put in sync the libraries of JEP, which is installed both on the Java/Kotlin side and Python.
We also update it to 4.1.0
> CON-1208: Put Jep in sync across Java and Python

- docs/docs/release-notes.md
These need to be added once we release 1.3.1 GA.
> Remove reference to upcoming 1.3.1 features in release notes

- docs/docs/enclave-configuration.md
- plugin-enclave-gradle/src/main/kotlin/com/r3/conclave/plugin/enclave/gradle/GenerateEnclaveMetadata.kt
- plugin-enclave-gradle/src/main/kotlin/com/r3/conclave/plugin/enclave/gradle/GradleEnclavePlugin.kt
This reverts commit d1f9bbdd5ef32a8a37d4fda3913ae4e4382c9fea from the release/1.3 branch, but it will still be present in the new release/1.3.1 branch.
> Revert "[CON-1135] Gradle plugin to output enclave metadata to file"

- plugin-enclave-gradle/src/main/kotlin/com/r3/conclave/plugin/enclave/gradle/AddEnclaveSignature.kt
- plugin-enclave-gradle/src/main/kotlin/com/r3/conclave/plugin/enclave/gradle/GenerateEnclaveMetadata.kt
- plugin-enclave-gradle/src/main/kotlin/com/r3/conclave/plugin/enclave/gradle/GenerateEnclaveSigningMaterial.kt
- plugin-enclave-gradle/src/main/kotlin/com/r3/conclave/plugin/enclave/gradle/GradleEnclavePlugin.kt
- plugin-enclave-gradle/src/main/kotlin/com/r3/conclave/plugin/enclave/gradle/LinuxExec.kt
- plugin-enclave-gradle/src/main/kotlin/com/r3/conclave/plugin/enclave/gradle/SignEnclave.kt
https://github.com/R3Conclave/conclave-core-sdk/pull/101 accidently made building on MacOS and Windows conditional on the new `buildInDocker` flag. This is not correct as Docker is always required for these environments.
> CON-1203: Non-Linux envs must always use Docker for building the enclave

- plugin-enclave-gradle/build.gradle
- plugin-enclave-gradle/src/main/kotlin/com/r3/conclave/plugin/enclave/gradle/GradleEnclavePlugin.kt
- versions.gradle
This avoids the need to duplicate the version string twice in the code base.
Also, updated the plugin to use the `Conclave-Release-Version` attribute value for the SDK version since it's set in all the jars, rather than having a duplicate entry under `Conclave-Version`.
> Passing the Conclave GraalVM version into the plugin jar manifest

- conclave-host/src/main/kotlin/com/r3/conclave/host/internal/gramine/GramineEnclaveHandle.kt
- integration-tests/general/mock-compatibility-tests/src/test/kotlin/com/r3/conclave/integrationtests/general/mockcompattests/MockEnclaveEnvironmentHardwareCompatibilityTest.kt
- integration-tests/general/tests/src/test/kotlin/com/r3/conclave/integrationtests/general/tests/CreatePostOfficeTests.kt
- integration-tests/general/tests/src/test/kotlin/com/r3/conclave/integrationtests/general/tests/DefaultEnclaveTests.kt
- integration-tests/general/tests/src/test/kotlin/com/r3/conclave/integrationtests/general/tests/EnclavePersistentMapTest.kt
- integration-tests/general/tests/src/test/kotlin/com/r3/conclave/integrationtests/general/tests/SealingTest.kt
- integration-tests/general/tests/src/test/kotlin/com/r3/conclave/integrationtests/general/tests/ThreadSafeEnclaveTests.kt
- integration-tests/general/tests/src/test/kotlin/com/r3/conclave/integrationtests/general/tests/filesystem/BufferedInputStreamTest.kt
- integration-tests/general/tests/src/test/kotlin/com/r3/conclave/integrationtests/general/tests/filesystem/DefaultFileSystemTest.kt
- integration-tests/general/tests/src/test/kotlin/com/r3/conclave/integrationtests/general/tests/filesystem/EnclaveRestartFileSystemTest.kt
- integration-tests/general/tests/src/test/kotlin/com/r3/conclave/integrationtests/general/tests/filesystem/FileInputStreamTest.kt
- integration-tests/general/tests/src/test/kotlin/com/r3/conclave/integrationtests/general/tests/filesystem/FileOutputStreamTest.kt
- integration-tests/general/tests/src/test/kotlin/com/r3/conclave/integrationtests/general/tests/filesystem/FileSystemInputStreamTest.kt
- integration-tests/general/tests/src/test/kotlin/com/r3/conclave/integrationtests/general/tests/filesystem/FilesTest.kt
- integration-tests/general/tests/src/test/kotlin/com/r3/conclave/integrationtests/general/tests/filesystem/MultiThreadedFileSystemTest.kt
- integration-tests/general/tests/src/test/kotlin/com/r3/conclave/integrationtests/general/tests/filesystem/PathsTest.kt
- integration-tests/general/tests/src/test/kotlin/com/r3/conclave/integrationtests/general/tests/filesystem/RenameTests.kt
- integration-tests/general/tests/src/test/kotlin/com/r3/conclave/integrationtests/general/tests/filesystem/SeekableByteChannelTest.kt
- integration-tests/general/tests/src/test/kotlin/com/r3/conclave/integrationtests/general/tests/filesystem/db/DatabaseEnclaveTest.kt
- integration-tests/pytorch-enclave/host/src/test/kotlin/com/r3/conclave/integrationtests/python/enclave/PytorchEnclaveTest.kt
- integration-tests/tribuo/client/src/test/kotlin/com/r3/conclave/integrationtests/tribuo/client/AnomalyDetectionTest.kt
- integration-tests/tribuo/client/src/test/kotlin/com/r3/conclave/integrationtests/tribuo/client/ClassificationTest.kt
- integration-tests/tribuo/client/src/test/kotlin/com/r3/conclave/integrationtests/tribuo/client/RegressionTest.kt
- integration-tests/tribuo/client/src/test/kotlin/com/r3/conclave/integrationtests/tribuo/client/TribuoTest.kt
Disable failing Gramine tests. Most of them are related to filesystem being not supported. 
New tickets were created to specify the failures. These are linked in the tests.
This PR gives green build of Gramine integration tests in Simulation mode.
Debug mode still fails on a new error, see https://r3-cev.atlassian.net/browse/CON-1165
> CON-1255: Mandate the Gramine integration tests for PRs

- scripts/ci_integration_tests.sh
There was a bug when checking for entered runtimeType. It would not print the entered type, but just print static string 'runtimeType'.
> Print entered runtimeType instead of a static string

- docs/docs/enclave-configuration.md
- docs/docs/release-notes.md
- integration-tests/pytorch-enclave/enclave/build.gradle
- plugin-enclave-gradle/src/main/kotlin/com/r3/conclave/plugin/enclave/gradle/ConclaveExtension.kt
- plugin-enclave-gradle/src/main/kotlin/com/r3/conclave/plugin/enclave/gradle/GradleEnclavePlugin.kt
- plugin-enclave-gradle/src/main/kotlin/com/r3/conclave/plugin/enclave/gradle/gramine/GenerateGramineBundle.kt
Added the configuration field `enclaveSize` to allow the end-user to specify the size of the enclave. By default the size is 4G.
> CON-1221 - Remove hardcoded enclave size for Gramine
